### ISSUE TITLE
Generator defaultCfg is shared between different generator instances

### ISSUE THREAD

**Issue by cestcedric** [kaeluka/mock-data-gen#7]
Hi,
Love this library!
But I found an issue:

### Setup
````js
it('creates independent generators', () => {
      const generator1 = gen(t.string);
      const firstValue1 = generator1.next().value;

      for (let i = 0; i < 10; i++) {
        generator1.next();
      }

      const generator2 = gen(t.string);
      const firstValue2 = generator2.next().value;

      expect(firstValue1).to.equal(firstValue2);
    });
````
### Expected result
Generators should be independent from one another and ``firstValue1`` should be equal to ``firstValue2``.

### Actual result
The extra iterations on ``generator1`` lead to a different result when calling ``generator2``.

**Comment by kaeluka** [comment]
Hey, @cestcedric! I'm so happy to hear it, I hope it's useful to you! Thank you for the issue and the nice PR. I've given it a quick look and will try the change out ASAP :)

**Comment by kaeluka** [comment]
![image](https://user-images.githubusercontent.com/775711/159116469-d1a93246-fa5d-4465-baaa-841183bbc9bd.png)
THANK YOU, have a nice weekend :)
